from applications.models import College

colleges = [
    College(
        collegeCode='001',
        className='机械工程学院',
    ),
    College(
        collegeCode='002',
        className='交通与车辆工程学院',
    ),
    College(
        collegeCode='003',
        className='农业工程与食品科学学院',
    ),
    College(
        collegeCode='004',
        className='电气与电子工程学院',
    ),
    College(
        collegeCode='005',
        className='计算机科学与技术学院',
    ),
    College(
        collegeCode='006',
        className='化学化工学院',
    ),
    College(
        collegeCode='007',
        className='建筑工程与空间信息学院',
    ),
    College(
        collegeCode='008',
        className='资源与环境工程学院',
    ),
    College(
        collegeCode='009',
        className='材料科学与工程学院',
    ),
    College(
        collegeCode='010',
        className='生命与医药学院',
    ),
    College(
        collegeCode='011',
        className='数学与统计学院',
    ),
    College(
        collegeCode='012',
        className='物理与光电工程学院',
    ),
    College(
        collegeCode='013',
        className='经济学院',
    ),
    College(
        collegeCode='014',
        className='管理学院',
    ),
    College(
        collegeCode='015',
        className='文学与新闻传播学院',
    ),
    College(
        collegeCode='016',
        className='外国语学院',
    ),
    College(
        collegeCode='017',
        className='法学院',
    ),
    College(
        collegeCode='018',
        className='马克思主义学院',
    ),
    College(
        collegeCode='019',
        className='美术学院',
    ),
    College(
        collegeCode='020',
        className='音乐学院',
    ),
    College(
        collegeCode='021',
        className='体育学院',
    ),
    College(
        collegeCode='022',
        className='鲁泰纺织服装学院',
    ),
    College(
        collegeCode='023',
        className='创新创业学院',
    ),
    College(
        collegeCode='024',
        className='国际教育学院',
    ),
    College(
        collegeCode='025',
        className='教师教育学院',
    ),
    College(
        collegeCode='026',
        className='信息管理学院',
    )
]