from applications.models import User, Role, Power
import datetime
now_time = datetime.datetime.now()


powerdata = [
    Power(
        id=1,
        name='系统管理',
        type='0',
        code='',
        url=None,
        open_type=None,
        parent_id='0',
        icon='layui-icon layui-icon-set-fill',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=2,
        name='用户管理',
        type='1',
        code='system:user:main',
        url='/system/user/',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon-rate',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=3,
        name='权限管理',
        type='1',
        code='system:power:main',
        url='/system/power/',
        open_type='_iframe',
        parent_id='1',
        icon=None,
        sort=2,
        create_time=now_time,
        enable=1,

    ), Power(
        id=4,
        name='角色管理',
        type='1',
        code='system:role:main',
        url='/system/role/',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-username',
        sort=2,
        create_time=now_time,
        enable=1,

    ), Power(
        id=5,
        name='日志管理',
        type='1',
        code='system:log:main',
        url='/system/log/',
        open_type='_iframe',
        parent_id='1',
        icon='layui-icon layui-icon-read',
        sort=4,
        create_time=now_time,
        enable=1,

    ),
     Power(
        id=6,
        name='权限增加',
        type='2',
        code='system:power:add',
        url='',
        open_type='',
        parent_id='3',
        icon='layui-icon layui-icon-add-circle',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=7,
        name='用户增加',
        type='2',
        code='system:user:add',
        url='',
        open_type='',
        parent_id='2',
        icon='layui-icon layui-icon-add-circle',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=8,
        name='用户编辑',
        type='2',
        code='system:user:edit',
        url='',
        open_type='',
        parent_id='2',
        icon='layui-icon layui-icon-rate',
        sort=2,
        create_time=now_time,
        enable=1,

    ), Power(
        id=9,
        name='用户删除',
        type='2',
        code='system:user:remove',
        url='',
        open_type='',
        parent_id='2',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,

    ), Power(
        id=10,
        name='权限编辑',
        type='2',
        code='system:power:edit',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,

    ), Power(
        id=11,
        name='权限删除',
        type='2',
        code='system:power:remove',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,

    ), Power(
        id=12,
        name='用户增加',
        type='2',
        code='system:role:add',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=1,
        create_time=now_time,
        enable=1,

    ), Power(
        id=13,
        name='角色编辑',
        type='2',
        code='system:role:edit',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=2,
        create_time=now_time,
        enable=1,

    ), Power(
        id=14,
        name='角色删除',
        type='2',
        code='system:role:remove',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=3,
        create_time=now_time,
        enable=1,

    ), Power(
        id=15,
        name='角色授权',
        type='2',
        code='system:role:power',
        url='',
        open_type='',
        parent_id='4',
        icon='',
        sort=4,
        create_time=now_time,
        enable=1,

    ),Power(
        id=16,
        name='体测成绩',
        type='1',
        code='student:data',
        url='/student/data/',
        open_type='_iframe',
        parent_id='17',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=1,
        create_time=now_time,
        enable=1,
    ),Power(
        id=17,
        name='体测管理',
        type='0',
        code='',
        url='',
        open_type='',
        parent_id='0',
        icon='layui-icon',
        sort=1,
        create_time=now_time,
        enable=1,
    ),Power(
        id=18,
        name='数据分析',
        type='1',
        code='student:show_small',
        url='/student/show_small/',
        open_type='_iframe',
        parent_id='17',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=1,
        create_time=now_time,
        enable=1,
    ),
    Power(
        id=19,
        name='成绩录入',
        type='1',
        code='student:addpage',
        url='/student/addpage/',
        open_type='_iframe',
        parent_id='17',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=1,
        create_time=now_time,
        enable=1,
    ),
    Power(
        id=20,
        name='学生信息',
        type='1',
        code='student:info',
        url='/student/info/',
        open_type='_iframe',
        parent_id='17',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=1,
        create_time=now_time,
        enable=1,
    ),
    Power(
        id=21,
        name='大屏展示',
        type='1',
        code='student:show',
        url='/student/show/',
        open_type='_blank',
        parent_id='0',
        icon='layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon layui-icon ',
        sort=1,
        create_time=now_time,
        enable=1,
    )
]
